@eAppointmentServer.WebAPI_HostAddress = https://localhost:7284

POST https://localhost:7284/api/Auth/Login
Accept: application/json
Content-Type: application/json

{
  "userNameOrEmail": "admin",
   "password": "1"
}
###
